export const tableData = {
  tableHeadings: [
    {
      id: 1,
      label: "DataTable_Id",
    },
    {
      id: 2,
      label: "Status",
    },
    {
      id: 3,
      label: "Customer",
    },
    {
      id: 4,
      label: "Estate",
    },
    {
      id: 5,
      label: "Total",
    },
    {
      id: 6,
      label: "Advance",
    },
    {
      id: 7,
      label: "Balance",
    },
  ],
  tableRows: [
    {
      id: "Dtx1",
      checked: false,
      status: "Approval",
      customer: "Michael Polansky",
      estate: "Leipzig, 13199",
      total: 18000,
      advance: 10000,
      balance: 8000,
    },
    {
      id: "Dtx2",
      checked: false,
      status: "Payment",
      customer: "Nicolas Johnson",
      estate: "Berlin, 14199",
      total: 15000,
      advance: 5000,
      balance: 10000,
    },
    {
      id: "Dtx3",
      checked: false,
      status: "Sign",
      customer: "Victor Soulman",
      estate: "Munich, 12199",
      total: 20000,
      advance: 10000,
      balance: 10000,
    },
    {
      id: "Dtx4",
      checked: false,
      status: "Briefing",
      customer: "Helen Howard",
      estate: "Berlin, 14199",
      total: 25000,
      advance: 15000,
      balance: 10000,
    },
    {
      id: "Dtx5",
      checked: false,
      status: "Payment",
      customer: "Sarah Williams",
      estate: "Leipzig, 13199",
      total: 22000,
      advance: 12000,
      balance: 10000,
    },
    {
      id: "Dtx6",
      checked: false,
      status: "Approval",
      customer: "James Thompson",
      estate: "Munich, 12199",
      total: 18000,
      advance: 10000,
      balance: 8000,
    },
    {
      id: "Dtx7",
      checked: false,
      status: "Sign",
      customer: "Emily Harris",
      estate: "Berlin, 14199",
      total: 25000,
      advance: 15000,
      balance: 10000,
    },
    {
      id: "Dtx8",
      checked: false,
      status: "Briefing",
      customer: "David Clark",
      estate: "Leipzig, 13199",
      total: 17000,
      advance: 9000,
      balance: 8000,
    },
    {
      id: "Dtx9",
      checked: false,
      status: "Approval",
      customer: "Sophia Turner",
      estate: "Munich, 12199",
      total: 19000,
      advance: 11000,
      balance: 8000,
    },
    {
      id: "Dtx10",
      checked: false,
      status: "Payment",
      customer: "Daniel Brown",
      estate: "Berlin, 14199",
      total: 23000,
      advance: 13000,
      balance: 10000,
    },
    {
      id: "Dtx11",
      checked: false,
      status: "Briefing",
      customer: "Lily Martin",
      estate: "Leipzig, 13199",
      total: 21000,
      advance: 14000,
      balance: 7000,
    },
    {
      id: "Dtx12",
      checked: false,
      status: "Sign",
      customer: "Benjamin Lee",
      estate: "Munich, 12199",
      total: 24000,
      advance: 15000,
      balance: 9000,
    },
    {
      id: "Dtx13",
      checked: false,
      status: "Approval",
      customer: "Olivia Moore",
      estate: "Berlin, 14199",
      total: 25000,
      advance: 15000,
      balance: 10000,
    },
    {
      id: "Dtx14",
      checked: false,
      status: "Payment",
      customer: "Jack Wilson",
      estate: "Leipzig, 13199",
      total: 16000,
      advance: 8000,
      balance: 8000,
    },
    {
      id: "Dtx15",
      checked: false,
      status: "Briefing",
      customer: "Chloe Scott",
      estate: "Munich, 12199",
      total: 20000,
      advance: 10000,
      balance: 10000,
    },
    {
      id: "Dtx16",
      checked: false,
      status: "Sign",
      customer: "Lucas Taylor",
      estate: "Berlin, 14199",
      total: 23000,
      advance: 13000,
      balance: 10000,
    },
    {
      id: "Dtx17",
      checked: false,
      status: "Approval",
      customer: "Ava Robinson",
      estate: "Leipzig, 13199",
      total: 22000,
      advance: 12000,
      balance: 10000,
    },
    {
      id: "Dtx18",
      checked: false,
      status: "Payment",
      customer: "Mason Hall",
      estate: "Munich, 12199",
      total: 20000,
      advance: 10000,
      balance: 10000,
    },
    {
      id: "Dtx19",
      checked: false,
      status: "Sign",
      customer: "Amelia Adams",
      estate: "Berlin, 14199",
      total: 18000,
      advance: 10000,
      balance: 8000,
    },
    {
      id: "Dtx20",
      checked: false,
      status: "Briefing",
      customer: "Ethan King",
      estate: "Leipzig, 13199",
      total: 21000,
      advance: 14000,
      balance: 7000,
    },
  ],
};
