export const todoData = [
  { id: "1", task: "Buy groceries", priority: "high", isCompleted: false },
  { id: "2", task: "Clean the house", priority: "medium", isCompleted: true },
  { id: "3", task: "Finish project report", priority: "high", isCompleted: false },
  { id: "4", task: "Book flight tickets", priority: "low", isCompleted: false },
  { id: "5", task: "Read a book", priority: "low", isCompleted: true },
  { id: "6", task: "Walk the dog", priority: "medium", isCompleted: false },
  { id: "7", task: "Call the plumber", priority: "high", isCompleted: true },
  { id: "8", task: "Prepare for meeting", priority: "high", isCompleted: false },
  { id: "9", task: "Organize the closet", priority: "low", isCompleted: true },
  { id: "10", task: "Plan weekend trip", priority: "medium", isCompleted: false },
  { id: "11", task: "Fix bike chain", priority: "medium", isCompleted: true },
  { id: "12", task: "Write blog post", priority: "high", isCompleted: false },
  { id: "13", task: "Learn a new recipe", priority: "low", isCompleted: false },
  { id: "14", task: "Pay utility bills", priority: "high", isCompleted: true },
  { id: "15", task: "Watch a documentary", priority: "low", isCompleted: true },
  { id: "16", task: "Practice guitar", priority: "medium", isCompleted: false },
  { id: "17", task: "Schedule a doctor’s appointment", priority: "high", isCompleted: false },
  { id: "18", task: "Attend yoga class", priority: "medium", isCompleted: true },
  { id: "19", task: "Update resume", priority: "high", isCompleted: false },
  { id: "20", task: "Buy a birthday gift", priority: "medium", isCompleted: true },
  { id: "21", task: "Repair the sink", priority: "high", isCompleted: false },
  { id: "22", task: "Water the plants", priority: "low", isCompleted: true },
  { id: "23", task: "Respond to emails", priority: "medium", isCompleted: false },
  { id: "24", task: "Complete online course", priority: "high", isCompleted: false },
  { id: "25", task: "Plan family dinner", priority: "low", isCompleted: true },
];
